name: waka-readme

on:
  # Trigger the workflow manually or on a daily schedule
  workflow_dispatch:
  schedule:
    # Runs daily at midnight UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: 🛠️ WakaReadme DevMetrics
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: 🔄 Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Update WakaTime Stats with Enhanced Visualization
      - name: 📊 Update WakaTime Statistics
        uses: athul/waka-readme@master
        with:
          ### 🔐 Authentication
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # GitHub token for committing changes
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # Your WakaTime API Key

          ### 🌐 API Configuration
          API_BASE_URL: https://wakatime.com/api # Alternative: https://wakapi.dev/api
          REPOSITORY: WhitV/WhitV # Target repository for the README update

          ### 🎨 Content Customization
          SHOW_TITLE: true # Display a title above the stats section
          SECTION_NAME: waka-stats # Unique identifier for the stats section
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿ # Enhanced ASCII blocks for rich visualization
          CODE_LANG: yaml # Syntax highlighting language for code blocks
          TIME_RANGE: last_7_days # Display stats for the last 7 days
          LANG_COUNT: 10 # Show top 10 languages
          SHOW_TIME: true # Display time spent per language
          SHOW_TOTAL: true # Include total coding time
          SHOW_MASKED_TIME: false # Exclude unclassified languages
          STOP_AT_OTHER: false # Continue listing languages beyond "Other"
          IGNORED_LANGUAGES: Binary YAML JSON TOML # Languages to exclude from stats

          ### 🌙 Dark Theme Customization
          GRAPH_COLOR: 1e1e1e # Dark background color for graphs
          TEXT_COLOR: ffffff # White text for high contrast
          BORDER_COLOR: 333333 # Subtle border color for graph elements

          ### ✨ Unique Design Enhancements
          CUSTOM_TITLE: "📈 My Coding Journey" # Custom title for the stats section
          ICONS: true # Include language icons next to names
          PROGRESS_BAR: true # Add progress bars for visual appeal

          ### 📝 Commit Settings
          COMMIT_MESSAGE: "✨ Update WakaTime metrics with a sleek design"
          TARGET_BRANCH: main # Branch to update
          TARGET_PATH: README.md # File to update
          COMMITTER_NAME: GitHubActionBot # Name for the commit author
          COMMITTER_EMAIL: action-bot@github.com # Email for the commit author
          AUTHOR_NAME: WhitV # Name of the commit author
          AUTHOR_EMAIL: sam123q12@gmail.com # Email of the commit author

          ### 🔧 Advanced Settings
          INCLUDE_EXTRA_STATS: true # Include additional WakaTime metrics
          FORMAT: markdown # Output format
