name: waka-readme
on:
  # Trigger workflow manually or based on schedule
  workflow_dispatch:
  schedule:
    # Runs daily at midnight UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Update WakaTime Stats
        uses: athul/waka-readme@master
        with:
          ### Authentication
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # GitHub token for committing
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # Your WakaTime API Key
          
          ### Meta Settings
          API_BASE_URL: https://wakatime.com/api # Use other services like Wakapi if needed
          REPOSITORY: WhitV/WhitV # Target repository for the README
          
          ### Content Customization
          SHOW_TITLE: true # Display title on the stats
          SECTION_NAME: waka-stats # Unique section name for stats
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿ # Enhanced ASCII art for better visualization
          CODE_LANG: yaml # Use YAML syntax highlighting for the stats
          TIME_RANGE: last_7_days # Display stats for the last 7 days
          LANG_COUNT: 10 # Show stats for the top 10 languages
          SHOW_TIME: true # Display time spent on each language
          SHOW_TOTAL: true # Include total coding time
          SHOW_MASKED_TIME: false # Do not include unclassified languages
          STOP_AT_OTHER: false # Continue listing languages even after "Other"
          IGNORED_LANGUAGES: Binary YAML JSON TOML # Exclude irrelevant languages

          ### Dark Theme Customization (Extra)
          GRAPH_COLOR: dark # Adjust for dark theme if the plugin supports it
          TEXT_COLOR: white # ตั้งค่าสีตัวหนังสือเป็นสีขาวเพื่อให้มองเห็นได้ชัดเจนบนพื้นหลังมืด

          ### Commit Settings
          COMMIT_MESSAGE: "Update WakaTime metrics with enhanced visualization"
          TARGET_BRANCH: main # Update stats on the main branch
          TARGET_PATH: README.md # Update README file
          COMMITTER_NAME: GitHubActionBot # Committer name for bot
          COMMITTER_EMAIL: action-bot@github.com # Committer email
          AUTHOR_NAME: WhitV # Author of the commit
          AUTHOR_EMAIL: sam123q12@gmail.com # Author's email

          ### Advanced Settings
          INCLUDE_EXTRA_STATS: true # Include extra WakaTime metrics (if applicable)
          FORMAT: markdown # Use Markdown for output
