name: waka-readme
on:
  # Trigger workflow manually or based on schedule
  workflow_dispatch:
  schedule:
    # Runs every 7 days (every Monday at midnight UTC)
    - cron: "17 17 * * 5"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Update WakaTime Stats
        uses: athul/waka-readme@master
        with:
          ### Authentication
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # GitHub token for committing
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # Your WakaTime API Key
          
          ### Meta Settings
          API_BASE_URL: https://wakatime.com/api # Use other services like Wakapi if needed
          REPOSITORY: WhitV/WhitV # Target repository for the README
          
          ### Content Customization
          SHOW_TITLE: true # Display title on the stats
          SECTION_NAME: waka-stats # Unique section name for stats
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿ # Enhanced ASCII art for better visualization
          CODE_LANG: yaml # Use YAML syntax highlighting for the stats
          
          ## Show stats for last 7 days
          TIME_RANGE: last_7_days # Show stats for the last 7 days
          LANG_COUNT: 10 # Show stats for the top 10 languages
          SHOW_TIME: true # Display time spent on each language
          SHOW_TOTAL: true # Show total coding time in the last 7 days
          
          ## Show total all-time stats
          SHOW_TOTAL_TIME: true # Show total coding time (all time)

          ### Commit Settings
          COMMIT_MESSAGE: "Update WakaTime metrics (Last 7 Days & All Time)"
          TARGET_BRANCH: main # Update stats on the main branch
          TARGET_PATH: README.md # Update README file
          COMMITTER_NAME: GitHubActionBot # Committer name for bot
          COMMITTER_EMAIL: action-bot@github.com # Committer email
          AUTHOR_NAME: WhitV # Author of the commit
          AUTHOR_EMAIL: sam123q12@gmail.com # Author's email
