name: waka-readme

on:
  # เรียกใช้งาน workflow ด้วยตนเองหรือกำหนดเวลา
  workflow_dispatch:
  schedule:
    # รันทุกวันตอนเที่ยงคืน UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: 🖥️ WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 🔄 Update WakaTime Stats
        uses: athul/waka-readme@master
        with:
          ### การยืนยันตัวตน
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # โทเค็น GitHub สำหรับการ commit
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # API Key ของ WakaTime

          ### การตั้งค่า Meta
          API_BASE_URL: https://wakatime.com/api # ใช้บริการอื่นเช่น Wakapi หากต้องการ
          REPOSITORY: WhitV/WhitV # Repository เป้าหมายสำหรับ README

          ### การปรับแต่งเนื้อหา
          SHOW_TITLE: true # แสดงชื่อหัวข้อสถิติ
          SECTION_NAME: waka-stats # ชื่อส่วนที่ไม่ซ้ำกันสำหรับสถิติ
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿ # อาร์ต ASCII ที่ปรับปรุงเพื่อการแสดงผลที่ดีขึ้น
          CODE_LANG: yaml # ใช้ไฮไลท์ไวยากรณ์ YAML สำหรับสถิติ
          TIME_RANGE: last_7_days # แสดงสถิติสำหรับ 7 วันที่ผ่านมา
          LANG_COUNT: 10 # แสดงสถิติสำหรับ 10 ภาษาแรก
          SHOW_TIME: true # แสดงเวลาที่ใช้กับแต่ละภาษา
          SHOW_TOTAL: true # รวมเวลาการเขียนโค้ดทั้งหมด
          SHOW_MASKED_TIME: false # ไม่รวมภาษาไม่ระบุหมวดหมู่
          STOP_AT_OTHER: false # ดำเนินการแสดงภาษาต่อไปแม้จะมี "Other"
          IGNORED_LANGUAGES: Binary YAML JSON TOML # ยกเว้นภาษาที่ไม่เกี่ยวข้อง

          ### การปรับแต่งธีมมืด (เพิ่มเติม)
          GRAPH_COLOR: "#1E1E1E" # สีพื้นหลังธีมมืด
          TEXT_COLOR: "#FFFFFF" # สีตัวหนังสือขาว
          BORDER_COLOR: "#444444" # สีขอบสำหรับกราฟ (ถ้ารองรับ)
          ACCENT_COLOR: "#FFD700" # สีเพิ่มเติมเพื่อความโดดเด่น

          ### การตั้งค่า Commit
          COMMIT_MESSAGE: "✨ Update WakaTime metrics with enhanced dark theme visualization"
          TARGET_BRANCH: main # อัพเดทสถิติบนสาขาหลัก
          TARGET_PATH: README.md # อัพเดทไฟล์ README
          COMMITTER_NAME: GitHubActionBot # ชื่อผู้ commit สำหรับบอท
          COMMITTER_EMAIL: action-bot@github.com # อีเมลผู้ commit
          AUTHOR_NAME: WhitV # ผู้เขียนของ commit
          AUTHOR_EMAIL: sam123q12@gmail.com # อีเมลของผู้เขียน

          ### การตั้งค่าขั้นสูง
          INCLUDE_EXTRA_STATS: true # รวมสถิติ WakaTime เพิ่มเติม (ถ้ามี)
          FORMAT: markdown # ใช้ Markdown สำหรับผลลัพธ์

          ### การปรับแต่งเพิ่มเติมสำหรับเอกลักษณ์
          CUSTOM_BADGE: "🎯" # เพิ่มไอคอนหรือตัวอักษรพิเศษเพื่อความโดดเด่น
          HEADER_STYLE: "border-bottom: 2px solid #FFD700;" # สไตล์ส่วนหัว (ถ้า plugin รองรับ)
