name: waka-readme

on:
  # สามารถเรียกใช้งาน workflow ได้ด้วยตนเองหรือกำหนดเวลา
  workflow_dispatch:
  schedule:
    # รันทุกวันเวลาเที่ยงคืน UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: 🛠️ WakaReadme DevMetrics
    runs-on: ubuntu-latest

    steps:
      # ขั้นตอนที่ 1: Checkout Repository
      - name: 🔄 Checkout Repository
        uses: actions/checkout@v3

      # ขั้นตอนที่ 2: อัปเดตสถิติ WakaTime
      - name: 📊 Update WakaTime Statistics
        uses: athul/waka-readme@master
        with:
          ### 🔐 Authentication
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # โทเคน GitHub สำหรับการ commit
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # API Key ของ WakaTime

          ### 🌐 Meta Settings
          API_BASE_URL: https://wakatime.com/api # ใช้บริการอื่น ๆ เช่น Wakapi หากต้องการ
          REPOSITORY: WhitV/WhitV # Repository เป้าหมายสำหรับการอัปเดต README

          ### 🎨 Content Customization
          SHOW_TITLE: true # แสดงหัวข้อบนส่วนสถิติ
          SECTION_NAME: waka-stats # ชื่อส่วนเฉพาะสำหรับสถิติ
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿ # ASCII art ที่เพิ่มความสวยงามให้กับกราฟ
          CODE_LANG: yaml # ใช้ syntax highlighting สำหรับ YAML
          TIME_RANGE: last_7_days # แสดงสถิติสำหรับ 7 วันที่ผ่านมา
          LANG_COUNT: 10 # แสดงสถิติสำหรับ 10 ภาษาแรก
          SHOW_TIME: true # แสดงเวลาที่ใช้ในแต่ละภาษา
          SHOW_TOTAL: true # รวมเวลาการเขียนโค้ดทั้งหมด
          SHOW_MASKED_TIME: false # ไม่รวมเวลาในภาษาที่ไม่ระบุประเภท
          STOP_AT_OTHER: false # แสดงภาษาต่อไปหลังจาก "Other"
          IGNORED_LANGUAGES: Binary YAML JSON TOML # ภาษาที่ไม่ต้องการแสดงในสถิติ

          ### ✨ Unique Design Enhancements
          CUSTOM_TITLE: "📈 My Coding Journey" # หัวข้อส่วนสถิติที่ปรับแต่งเอง
          ICONS: true # แสดงไอคอนของภาษา
          PROGRESS_BAR: true # เพิ่มแถบความคืบหน้าเพื่อความสวยงาม

          ### 📝 Commit Settings
          COMMIT_MESSAGE: "✨ Update WakaTime metrics with a sleek design"
          TARGET_BRANCH: main # สาขาที่ต้องการอัปเดต
          TARGET_PATH: README.md # ไฟล์ที่ต้องการอัปเดต
          COMMITTER_NAME: GitHubActionBot # ชื่อผู้ commit
          COMMITTER_EMAIL: action-bot@github.com # อีเมลของผู้ commit
          AUTHOR_NAME: WhitV # ชื่อผู้เขียน commit
          AUTHOR_EMAIL: sam123q12@gmail.com # อีเมลของผู้เขียน commit

          ### 🔧 Advanced Settings
          INCLUDE_EXTRA_STATS: true # รวมสถิติเพิ่มเติมจาก WakaTime (ถ้ามี)
          FORMAT: markdown # รูปแบบการแสดงผลเป็น Markdown
